edition = "2018"
unstable_features = true
combine_control_expr = false
comment_width = 120
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 25
struct_field_align_threshold = 25
format_code_in_doc_comments = true
format_macro_matchers = true
imports_granularity = "Crate"
hide_parse_errors = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
use_try_shorthand = false
